#!/bin/sh
# Sample /etc/qemu-ifup to have bridged networking between qemu instances and your real net
# You need "youruser ALL=(root) NOPASSWD: /etc/qemu-ifup" in /etc/sudoers
# You also need enough rights on /dev/tun

# script to bring up the tun device in QEMU in bridged mode
# first parameter is name of tap device (e.g. tap0)

#
# some constants specific to the local host - change to suit your host
#
ETH0IPADDR=172.16.157.100
MASK=255.255.255.0
GATEWAY=172.16.157.1
BROADCAST=172.16.157.255
#
# First take ens33  down, then bring it up with IP address 0.0.0.0 
#
/sbin/ifdown ens33
/sbin/ifconfig ens33 0.0.0.0 promisc up
#
# Bring up the tap device (name specified as first argument, by QEMU)
#
/usr/sbin/openvpn --mktun --dev $1 --user `id -un`
/sbin/ifconfig $1 0.0.0.0 promisc up
#
# create the bridge between ens33 and the tap device
#
/sbin/brctl addbr br0
/sbin/brctl addif br0 ens33
/sbin/brctl addif br0 $1
# 
# only a single bridge so loops are not possible, turn off spanning tree
# protocol
#
/sbin/brctl stp br0 off 
# 
# Bring up the bridge with ETH0IPADDR and add the default route 
#
/sbin/ifconfig br0 $ETH0IPADDR netmask $MASK broadcast $BROADCAST
/sbin/route add default gw $GATEWAY
#
# stop firewall - comment this out if you don't use Firestarter
#
/usr/sbin/service firestarter stop
