#!/bin/sh 
# 
# Script to bring down and delete bridge br0 when QEMU exits 
# 
# Bring down ens33 and br0 
#
/sbin/ifdown ens33
/sbin/ifdown br0
/sbin/ifconfig br0 down 
# 
# Delete the bridge
#
sbin/brctl delbr br0 
# 
# bring up ens33 in "normal" mode 
#
/sbin/ifconfig ens33 -promisc
/sbin/ifup ens33
#
# delete the tap device
#
/usr/sbin/openvpn --rmtun --dev $1
#
# start firewall again
# 
/usr/sbin/service firestarter start
