/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bbtechlab_hellojni_helloStringJNI */

#ifndef _Included_com_bbtechlab_hellojni_helloStringJNI
#define _Included_com_bbtechlab_hellojni_helloStringJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bbtechlab_hellojni_helloStringJNI
 * Method:    getStringJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bbtechlab_hellojni_helloStringJNI_getStringJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
