/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     HelloJNI
 * Method:    average
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_HelloJNI_average
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     HelloJNI
 * Method:    stringJNI
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HelloJNI_stringJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     HelloJNI
 * Method:    sumAndAverage
 * Signature: ([I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_HelloJNI_sumAndAverage
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     HelloJNI
 * Method:    modifyInstanceVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloJNI_modifyInstanceVariable
  (JNIEnv *, jobject);

/*
 * Class:     HelloJNI
 * Method:    modifyStaticVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloJNI_modifyStaticVariable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
